version: "3.9"
services:
  logger:
    image: ubuntu/apache2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs-nginx.entrypoints=https"
      - "traefik.http.routers.logs-nginx.rule=Host(`logs.${HOST}`) && Path(`/logger`)"
      - "traefik.http.routers.logs-nginx.tls=true"
      - "traefik.http.routers.logs-nginx.tls.certresolver=letsEncrypt"
      - "traefik.http.services.logs-nginx-service.loadbalancer.server.port=80"
      - "traefik.docker.network=webproxy"
    logging:
      driver: loki
      options:
        loki-url: "https://loki:loki123@loki.t.realmanual.ru/loki/api/v1/push"
    expose:
     - 80
    networks:
      - loki
      - webproxy

networks:
  loki:
    name: loki
  webproxy:
    name: webproxy
